NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.rs1.hospital.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.rs1.hospital.com-cert.pem
    OrganizationalUnitIdentifier: peer
