version: '2'

volumes:
  peer0.rs2.hospital.com:
  peer1.rs2.hospital.com:

services:

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-rs2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.rs2.hospital.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3abd002132b7d2f723290fed5f77c5c24a017147fe901a09938dd39b8ddd3cb0_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.rs2.hospital.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3abd002132b7d2f723290fed5f77c5c24a017147fe901a09938dd39b8ddd3cb0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/rs2.hospital.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerrs2

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for hospital map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "7984:5984"

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for hospital map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"

  peer0.rs2.hospital.com:
    container_name: peer0.rs2.hospital.com
    extends:
      file:  base/docker-compose-base3.yaml
      service: peer0.rs2.hospital.com
    depends_on:
      - couchdb2

  peer1.rs2.hospital.com:
    container_name: peer1.rs2.hospital.com
    extends:
      file:  base/docker-compose-base3.yaml
      service: peer1.rs2.hospital.com
    depends_on:
      - couchdb3
